version: '2'

services:
  data_manager:
    command: python Data_Manager.py
    depends_on:
      - data_store
    container_name: data_manager_01
    image: madderle/twitter-sentiment-analysis:data-manager-1.0

  data_store:
    image: redis:alpine
