version: '2'

services:
  data_manager:
    command: python Data_Manager.py
    depends_on:
      - data_store
    container_name: twitter_data_manager
    ports:
      - "9999:9999"
    image: madderle/twitter-sentiment-analysis:data-manager-2.0
    environment:
     - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/home/ds

  data_store:
    container_name: twitter_data_store
    image: redis:alpine
    ports:
      - 6379:6379
